// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB3X4owoxCOTJx42hWdyLi9i3FEKw46r4',
    appId: '1:1022157797500:web:e8782d852b45be2f9031f9',
    messagingSenderId: '1022157797500',
    projectId: 'gen-lang-client-0841432940',
    authDomain: 'gen-lang-client-0841432940.firebaseapp.com',
    storageBucket: 'gen-lang-client-0841432940.firebasestorage.app',
    measurementId: 'G-4Y1HJ209G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9mgk_f0zVm6MagRp2oISRerdWEOoGVI0',
    appId: '1:1022157797500:android:507aebc49f83c9ac9031f9',
    messagingSenderId: '1022157797500',
    projectId: 'gen-lang-client-0841432940',
    storageBucket: 'gen-lang-client-0841432940.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaAjuCJBGccAGQ8tJ1MRv17saHdtG1FP8',
    appId: '1:1022157797500:ios:604a66f3b9ffa74f9031f9',
    messagingSenderId: '1022157797500',
    projectId: 'gen-lang-client-0841432940',
    storageBucket: 'gen-lang-client-0841432940.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaAjuCJBGccAGQ8tJ1MRv17saHdtG1FP8',
    appId: '1:1022157797500:ios:604a66f3b9ffa74f9031f9',
    messagingSenderId: '1022157797500',
    projectId: 'gen-lang-client-0841432940',
    storageBucket: 'gen-lang-client-0841432940.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB3X4owoxCOTJx42hWdyLi9i3FEKw46r4',
    appId: '1:1022157797500:web:db3f7b173a5375cd9031f9',
    messagingSenderId: '1022157797500',
    projectId: 'gen-lang-client-0841432940',
    authDomain: 'gen-lang-client-0841432940.firebaseapp.com',
    storageBucket: 'gen-lang-client-0841432940.firebasestorage.app',
    measurementId: 'G-QXFG0FWQ9Z',
  );
}
